import { Scene } from 'phaser';
import { setPosition, setScene, addToInventory, removeFromInventory, setVictory, setGameOver, setOxygen, debugSetOxygen, setPaused } from '../debug';
import { Player } from '../entities/Player';
import { Key } from '../entities/Key';
import { Door } from '../entities/Door';

const TILE = 32;

//  Gameplay anchors in PIXELS. The map is generated by
//  game/maps/build_map.py — if the layout changes there, change these to
//  match (they are the tile centers of build_map.py's SPAWN_TILE / KEY_TILE
//  / DOOR_TILE / EXIT_TILE).
const LAYOUT = {
    spawn: { x: 7 * TILE + 16, y: 19 * TILE + 16 },
    key: { x: 31 * TILE + 16, y: 8 * TILE + 16 },
    door: { x: 34 * TILE + 16, y: 31 * TILE + 16 },
    exit: { x: 37 * TILE + 16, y: 31 * TILE + 16 },
};

//  Door-threshold fix: the door only opens when the player is squarely in
//  front of it (centers aligned within this many px on the approach axis),
//  not when a diagonal graze clips the corner of the door body.
const DOOR_APPROACH_TOLERANCE = 12;

export class Game extends Scene
{
    private player!: Player;
    private key!: Key;
    private door!: Door;
    private doorOpened = false;
    private oxygen = 100;
    private oxygenTimer!: Phaser.Time.TimerEvent;
    private isPaused = false;
    private hudText!: Phaser.GameObjects.Text;

    constructor ()
    {
        super('Game');
    }

    //  Phaser scene lifecycle — invoked by the Scene Manager, no direct call site.
    //  fallow-ignore-next-line unused-class-member
    create ()
    {
        setScene('Game');
        setOxygen(100);
        debugSetOxygen(100);
        setPaused(false);
        this.oxygen = 100;
        this.isPaused = false;

        const map = this.make.tilemap({ key: 'dungeon' });
        const tiles = map.addTilesetImage('dungeon', 'dungeon-tiles');
        const layer = map.createLayer('Dungeon', tiles!, 0, 0)!;

        //  Kenney tileset: gid 1/4-6 = floor, gid 2 = wall, gid 3 = void.
        //  Wall and void both block movement.
        map.setCollisionBetween(2, 3, true, false, 'Dungeon');

        //  Arcade world bounds default to the CANVAS size (640x480), not the
        //  map — with collideWorldBounds the player would hit an invisible
        //  wall long before the vault (blocked BL-006).
        this.physics.world.setBounds(0, 0, map.widthInPixels, map.heightInPixels);

        this.player = new Player(this, LAYOUT.spawn.x, LAYOUT.spawn.y);
        this.key = new Key(this, LAYOUT.key.x, LAYOUT.key.y);
        this.door = new Door(this, LAYOUT.door.x, LAYOUT.door.y);

        // Ensure the door is positioned at the exact tile boundary so it fully blocks the tile
        const doorBody = this.door.body as Phaser.Physics.Arcade.Body;
        doorBody.setSize(32, 32);
        doorBody.setOffset(0, 0);

        this.physics.add.collider(this.player, layer);
        this.physics.add.collider(this.player, this.door, this.openDoor, undefined, this);
        this.physics.add.overlap(this.player, this.key, this.pickUpKey, undefined, this);

        //  Exit trigger: an invisible zone in the vault's east half, behind
        //  the locked door — the dark doorway sprite marks it visually.
        this.add.image(LAYOUT.exit.x, LAYOUT.exit.y, 'exit-doorway');
        const exitZone = this.add.zone(LAYOUT.exit.x, LAYOUT.exit.y, 32, 32);
        this.physics.add.existing(exitZone, true);  // immovable static body
        this.physics.add.overlap(this.player, exitZone, this.triggerVictory, undefined, this);

        // Oxygen timer: drain 1 unit per second. When it hits 0, game over.
        this.oxygenTimer = this.time.addEvent({
            delay: 1000,
            callback: () => {
                // Do not drain oxygen while paused
                if (this.isPaused) {
                    return;
                }
                const query = new URLSearchParams(window.location.search);
                const fastOxygen = query.get('fastOxygen');
                const drainRate = fastOxygen === '1' ? 10 : 1;
                this.oxygen = Math.max(0, this.oxygen - drainRate);
                setOxygen(this.oxygen);
                debugSetOxygen(this.oxygen);
                if (this.oxygen <= 0) {
                    this.triggerGameOver();
                }
            },
            loop: true
        });

        // Spacebar toggles pause
        this.input.keyboard!.on('keydown-SPACE', () => {
            if (this.isPaused) {
                this.resumeGame();
            } else {
                this.pauseGame();
            }
        });

        // HUD: fixed to camera, top-left corner
        this.hudText = this.add.text(10, 10, '', {
            fontFamily: 'Arial', fontSize: 18, color: '#ffffff',
            stroke: '#000000', strokeThickness: 4,
        }).setScrollFactor(0).setDepth(1000);

        this.cameras.main.setBounds(0, 0, map.widthInPixels, map.heightInPixels);
        this.cameras.main.startFollow(this.player, true, 0.1, 0.1);
    }

    //  Phaser scene lifecycle — invoked by the Scene Manager, no direct call site.
    //  fallow-ignore-next-line unused-class-member
    update (): void
    {
        // Still update the player (so input state stays fresh), but
        // freeze movement and world updates while paused.
        if (this.isPaused) {
            const body = this.player.body as Phaser.Physics.Arcade.Body;
            body.setVelocity(0, 0);
            return;
        }
        this.player.update();
        this.key.update();
        this.door.update();
        setPosition(this.player.x, this.player.y);
        this.updateHud();
    }

    private updateHud (): void
    {
        const state = (window as any).__game?.state;
        const keys = state?.inventory?.keys ?? 0;
        this.hudText.setText(`Keys: ${keys}`);
    }

    private pauseGame (): void
    {
        this.isPaused = true;
        setPaused(true);
        // Freeze the player immediately
        const body = this.player.body as Phaser.Physics.Arcade.Body;
        body.setVelocity(0, 0);
        this.physics.world.pause();
    }

    private resumeGame (): void
    {
        this.isPaused = false;
        setPaused(false);
        this.physics.world.resume();
    }

    private pickUpKey (player: Phaser.GameObjects.GameObject, key: Phaser.GameObjects.GameObject)
    {
        if (!key.active || this.isPaused) {
            return;
        }
        key.destroy();
        addToInventory('keys');
    }

    private openDoor (player: Phaser.GameObjects.GameObject, door: Phaser.GameObjects.GameObject)
    {
        const doorSprite = door as Door;
        if (doorSprite.active && !this.doorOpened && !this.isPaused)
        {
            //  Door-threshold fix: a diagonal graze clipping the door's
            //  corner must not consume the key — the player has to be
            //  squarely in front of the door (the vault door sits in a
            //  vertical wall, so the approach is horizontal and the y
            //  centers must align).
            const playerSprite = player as Player;
            if (Math.abs(playerSprite.y - doorSprite.y) > DOOR_APPROACH_TOLERANCE)
            {
                return;
            }
            // Check if the player has a key
            const state = (window as any).__game?.state;
            if (state && state.inventory.keys > 0)
            {
                // Open the door and consume the key
                this.doorOpened = true;
                doorSprite.open();
                removeFromInventory('keys');
            }
        }
    }

    private triggerVictory (player: Phaser.GameObjects.GameObject, exit: Phaser.GameObjects.GameObject)
    {
        if (!this.doorOpened || this.isPaused) {
            // The exit should only trigger after the door is unlocked/open.
            return;
        }
        // Stop the oxygen timer when the game ends
        this.oxygenTimer.remove();
        setPaused(false);
        // Transition to the Victory scene and mark it in the debug state.
        setVictory();
        this.scene.start('Victory');
    }

    private triggerGameOver ()
    {
        // Stop the oxygen timer to prevent re-triggering
        this.oxygenTimer.remove();
        setPaused(false);
        setGameOver();
        this.scene.start('GameOver');
    }
}
